language: node_js

notifications:
  email: false

node_js:
  - '12'

jobs:
  include:
    - name: "Sauce test"
      script: |
        node scripts/prepare-for-npm
        cd browser-test
        npm ci
        npm run sauce

    - env: TZ=Asia/Tehran
      script: npm run test

    - env: TZ=Europe/Paris
      script: npm run test

    - env: TZ=Australia/Canberra
      script: npm run test

    - env: TZ=America/Tijuana
      script: npm run test

    - stage: deploy
      deploy:
        on:
          branch: master
          tags: true
        provider: script
        skip_cleanup: true
        script: |
          echo "Deploying to npm (node $(node -v), TZ $TZ)"
          date +'%D %T %:z (%Z)'
          node scripts/prepare-for-npm
          sh scripts/deploy.sh $TRAVIS_TAG

